linter:
  rules:
    prefer_single_quotes: true 
    always_declare_return_types: true

# Additional information about this file can be found at
# https://dart.dev/tools/linter-rules
# https://dart.dev/guides/language/analysis-options
